version: '3.8'

services:
  app:
    build: .
    container_name: bank-management-system
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=banking_db
      - DB_USERNAME=banking_user
      - DB_PASSWORD=banking_password
      - JWT_SECRET=4TUg6ciwT+vunAqvkNi/Y4N+XyrF570mECkSH/dxTKU=
      - JAVA_OPTS=-Xmx512m -Xms256m
    ports:
      - "8082:8080" # Host:Container
    networks:
      - banking-network
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: banking-db
    environment:
      - POSTGRES_DB=banking_db
      - POSTGRES_USER=banking_user
      - POSTGRES_PASSWORD=banking_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - banking-network
    restart: unless-stopped

networks:
  banking-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local